### ISSUE TITLE
batch options not supported

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-ctffind#3]
ctffind cant run on several mics at once, so what's the point of using batches?

**Comment by delarosatrevin** [comment]
Maybe in the future, the batch option could be added and we already have the infrastructure in place. Moreover, in streaming, it does not make sense to schedules steps with single item to process and have extra IO (checking input DB, updating output one) if the CTF estimation is faster. So, even if internally all jobs are launched sequentially, it might still benefit from reducing the scheduling and synchronization overhead.
